dist: trusty
cache:
  - bundler
addons:
  postgresql: "9.6"
language: ruby
rvm:
 - 2.3.1
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
script: bundle exec rspec spec
